name: Continous Integration
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
       
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Install dependencies
        run: npm install

      - name: Check code style
        run: npm run lint

      - name: Generate a random JWT secret
        id: generate-secret
        run: |
          JWT_SECRET=$(openssl rand -base64 40)
          echo "JWT_SECRET=$JWT_SECRET" >> $GITHUB_OUTPUT
        shell: bash
     

      - name: Prepare enviroment
        run: npm run infra:start

      - name: Run tests
        run: npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/whispering-database
          PORT: 3000
          SALT_ROUNDS: 10
          JWT_SECRET: ${{ steps.generate-secret.outputs.JWT_SECRET }}
